# Configure app VM get nginx up and running, and set up our demo app.
---

- hosts: web
  gather_facts: yes
  become: true
  tasks:
  - name: copying file over to web VM
    copy:
      src: /home/vagrant/app
      dest: /home/vagrant/

  - name: copying reverse proxy config over to web VM
    copy:
      src: /home/vagrant/app/default
      dest: /etc/nginx/sites-available/

  - name: set env var DB_HOST
    become_user: vagrant
    lineinfile:
      path: /home/vagrant/.bashrc
      line: export DB_HOST='mongodb://192.168.33.11:27017/posts'
      create: yes

  - name: download a specific version of nodejs
    shell: curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -

  - name: install the required packages (with downloaded nodejs downgrade)
    apt:
      pkg:
        - nginx
        - nodejs
        - npm
      update_cache: yes

  - name: nginx restart
    service: name=nginx state=restarted

  - name: nginx enable
    service: name=nginx enabled=yes

  - name: install and run the app
    become_user: vagrant
    environment:
      DB_HOST='mongodb://192.168.33.11:27017/posts'
    shell:
      cd app; node seeds/seed.js; npm install; screen -d -m npm start